CREATE SCHEMA ChordNet;

CREATE TABLE ChordLog (
  ChordID INTEGER NOT NULL AUTO_INCREMENT,
  RootNote VARCHAR(10) NOT NULL,
  ChordName VARCHAR(50) NOT NULL,
  PredictedLabel VARCHAR(25) NOT NULL,
  ActualLabel VARCHAR(25) NOT NULL,
  ChordDateTime DATETIME NOT NULL,
  WaveType VARCHAR(25) NOT NULL,
  CONSTRAINT PK_ChordLog PRIMARY KEY (ChordID) );