CREATE TABLE CreateWave (
WaveID INT NOT NULL AUTO_INCREMENT,
NoteLabels VARCHAR(500) NOT NULL, 
WaveType VARCHAR(25) NOT NULL, 
WtPos FLOAT NOT NULL,
Duration FLOAT NOT NULL, 
BPM FLOAT NOT NULL, 
TimeMode VARCHAR(10) NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_WaveID PRIMARY KEY (WaveID) 
);

CREATE TABLE Rest (
RestID INT NOT NULL AUTO_INCREMENT,
Rhythm FLOAT NOT NULL,
BPM FLOAT NOT NULL, 
TimeMode VARCHAR(10) NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_RestID PRIMARY KEY (RestID) 
);

CREATE TABLE Sequence (
SequenceID INT NOT NULL AUTO_INCREMENT,
NoteLabels VARCHAR(500) NOT NULL, 
WaveType VARCHAR(25) NOT NULL, 
WtPos FLOAT NOT NULL,
Rhythm FLOAT NOT NULL,  
Duration FLOAT NOT NULL,  
ArpType VARCHAR(50) NOT NULL, 
FadeIn FLOAT NOT NULL,  
FadeOut FLOAT NOT NULL,  
InCurve FLOAT NOT NULL,  
OutCurve FLOAT NOT NULL, 
BPM FLOAT NOT NULL, 
TimeMode VARCHAR(10) NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_SequenceID PRIMARY KEY (SequenceID) 
);

CREATE TABLE Arpeggio (
ArpeggioID INT NOT NULL AUTO_INCREMENT,
ChordLabel VARCHAR(50) NOT NULL,
RootNote VARCHAR(5) NOT NULL,
WaveType VARCHAR(25) NOT NULL, 
WtPos FLOAT NOT NULL,
Rhythm FLOAT NOT NULL,  
Duration FLOAT NOT NULL,  
ArpType VARCHAR(25) NOT NULL, 
TonalSystem FLOAT NOT NULL,
FadeIn FLOAT NOT NULL,  
FadeOut FLOAT NOT NULL,  
InCurve FLOAT NOT NULL,  
OutCurve FLOAT NOT NULL, 
BPM FLOAT NOT NULL, 
TimeMode VARCHAR(10) NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_ArpeggioID PRIMARY KEY (ArpeggioID) 
);

CREATE TABLE Chord (
ChordID INT NOT NULL AUTO_INCREMENT,
ChordLabel VARCHAR(50) NOT NULL,
RootNote VARCHAR(5) NOT NULL,
WaveType VARCHAR(25) NOT NULL, 
WtPos FLOAT NOT NULL,
Duration FLOAT NOT NULL,
TonalSystem FLOAT NOT NULL,
FadeIn FLOAT NOT NULL,
FadeOut FLOAT NOT NULL,
InCurve FLOAT NOT NULL,
OutCurve FLOAT NOT NULL,
BPM FLOAT NOT NULL, 
TimeMode VARCHAR(10) NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_ChordID PRIMARY KEY (ChordID) 
);

CREATE TABLE Sample (
SampleID INT NOT NULL AUTO_INCREMENT,
SoundCategory VARCHAR(50) NOT NULL, 
FileName VARCHAR(500) NOT NULL, 
Duration FLOAT NOT NULL,
NumChannels INT NOT NULL,
SampleRate INT NOT NULL,
MaxVol FLOAT NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_SampleID PRIMARY KEY (SampleID) 
);

CREATE TABLE LoopMethod (
LoopID INT NOT NULL AUTO_INCREMENT,
NumLoops FLOAT NOT NULL,
NumChannels FLOAT NOT NULL,
BPM FLOAT NOT NULL, 
TimeMode VARCHAR(10) NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_LoopID PRIMARY KEY (LoopID) 
);

CREATE TABLE TimeMethod (
TimeID INT NOT NULL AUTO_INCREMENT,
Duration FLOAT NOT NULL,
BPM FLOAT NOT NULL, 
TimeMode VARCHAR(10) NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_TimeID PRIMARY KEY (TimeID) 
);

CREATE TABLE TimeEdit (
TimeEditID INT NOT NULL AUTO_INCREMENT,
OldDuration FLOAT NOT NULL,
NewDuration FLOAT NOT NULL,
BPM FLOAT NOT NULL, 
TimeMode VARCHAR(10) NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_TimeEditID PRIMARY KEY (TimeEditID) 
);

CREATE TABLE Reverse (
ReverseID INT NOT NULL AUTO_INCREMENT,
Duration FLOAT NOT NULL,
NumChannels FLOAT NOT NULL,
BPM FLOAT NOT NULL, 
TimeMode VARCHAR(10) NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_ReverseID PRIMARY KEY (ReverseID) 
);

CREATE TABLE Volume (
VolumeID INT NOT NULL AUTO_INCREMENT,
VolumeFactor FLOAT NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_VolumeID PRIMARY KEY (VolumeID) 
);

CREATE TABLE LoopMethod (
LoopID INT NOT NULL AUTO_INCREMENT,
LoopCount INT NOT NULL,
BPM FLOAT NOT NULL, 
TimeMode VARCHAR(10) NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_LoopID PRIMARY KEY (LoopID) 
);

CREATE TABLE Pan (
PanID INT NOT NULL AUTO_INCREMENT, 
PanFactor VARCHAR(5),
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_PanID PRIMARY KEY (PanID) 
);

CREATE TABLE Fade (
FadeID INT NOT NULL AUTO_INCREMENT,
FadeIn FLOAT NOT NULL,
FadeOut FLOAT NOT NULL,
InCurve FLOAT NOT NULL,
OutCurve FLOAT NOT NULL,
CurveType VARCHAR(5),
BPM FLOAT NOT NULL, 
TimeMode VARCHAR(10) NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_FadeID PRIMARY KEY (FadeID) 
);

CREATE TABLE LPF (
LPFID INT NOT NULL AUTO_INCREMENT,
Cutoff FLOAT NOT NULL,
FilterOrder FLOAT NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_LPFID PRIMARY KEY (LPFID) 
);

CREATE TABLE HPF (
HPFID INT NOT NULL AUTO_INCREMENT,
Cutoff FLOAT NOT NULL,
FilterOrder FLOAT NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_HPFID PRIMARY KEY (HPFID) 
);

CREATE TABLE LFO (
LFOID INT NOT NULL AUTO_INCREMENT,
Frequency FLOAT NOT NULL,
WaveType VARCHAR(25) NOT NULL, 
WtPos FLOAT NOT NULL,
Volume FLOAT NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_LFOID PRIMARY KEY (LFOID) 
);

CREATE TABLE Delay (
DelayID INT NOT NULL AUTO_INCREMENT,
Time FLOAT NOT NULL,
Feedback INT NOT NULL,
Mix INT NOT NULL,
Spread INT NOT NULL,
Stereo BOOLEAN NOT NULL,
Sync BOOLEAN NOT NULL,
StartSide VARCHAR(6) NOT NULL,
BPM FLOAT NOT NULL, 
TimeMode VARCHAR(10) NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_DelayID PRIMARY KEY (DelayID) 
);

CREATE TABLE Bounce (
BounceID INT NOT NULL AUTO_INCREMENT,
FileName VARCHAR(500) NOT NULL,
Duration FLOAT NOT NULL,
SampleRate INT NOT NULL,
NumChannels INT NOT NULL,
MaxVol FLOAT NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_BounceID PRIMARY KEY (BounceID) 
);

CREATE TABLE ViewMethod (
ViewID INT NOT NULL AUTO_INCREMENT,
Duration FLOAT NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_ViewID PRIMARY KEY (ViewID) 
);

CREATE TABLE AddWaves (
AddWavesID INT NOT NULL AUTO_INCREMENT,
TotalWaves INT NOT NULL,
NumChannels INT NOT NULL,
AddContext VARCHAR(25) NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_AddWavesID PRIMARY KEY (AddWavesID) 
);

CREATE TABLE JoinWaves (
JoinWavesID INT NOT NULL AUTO_INCREMENT,
TotalWaves INT NOT NULL,
NumChannels INT NOT NULL,
JoinContext VARCHAR(25) NOT NULL,
UserID VARCHAR(50) NOT NULL, 
EventDateTime DATETIME NOT NULL,
CONSTRAINT PK_JoinWavesID PRIMARY KEY (JoinWavesID) 
);
